### ISSUE TITLE
Take out open-gpt.app and knowbuddy.ai from the readme, such PREDATORY scams

### ISSUE THREAD

**Issue by fdovila** [OpenMindClub/awesome-chatgpt#10]
I tried using both...
the first didn't even run the test, and asked to subscribe and pay. While it shows a message :🙇 There are too many users to afford the cost of OpenAI, and the free use is temporarily closed. Paid users are not affected."

The second is asking $1 USD per every 5 messages???? Really?

On the positive side, I don't see you mentioning https://poe.com/ made by Quora. I believe is the best non opeanai product so far. It's paid, but accessing Claude+, Sage, Dragonfly and GPT-4 for the same price is awesome.

**Comment by asiyoua** [comment]
For knowbuddy, the website is down, I have deleted the URL.

I had mentioned poe in Competitors: AI ChatBot. 
But thank you for your reminder, I found that the previous category was not suitable. It has now been moved to the web app section.

If you find anything else, please feel free to raise an issue, thank you.
