### ISSUE TITLE
Information to be supplemented (Dev)

### ISSUE THREAD

**Issue by ipruning** [OpenMindClub/awesome-chatgpt#4]
- https://github.com/logspace-ai/langflow
- https://github.com/hwchase17/langchain
- https://github.com/microsoft/semantic-kernel
- https://github.com/emptycrown/llama-hub
- https://github.com/ShreyaR/guardrails

**Comment by ipruning** [comment]
- https://github.com/circlestarzero/EX-chatGPT
- https://github.com/kaixindelele/ChatPaper
- https://github.com/mayooear/gpt4-pdf-chatbot-langchain

**Comment by Lilhxr** [comment]
ChartPaper is pretty Good✨

**Comment by ipruning** [comment]
- https://github.com/ading2210/poe-api If you want to test that Claude+ Poe may be the only route, this repository offers a nice wrapper.

**Comment by ipruning** [comment]
- https://github.com/mayooear/gpt4-pdf-chatbot-langchain

**Comment by ipruning** [comment]
- https://github.com/Azure-Samples/azure-search-openai-demo
